services:
  - type: web
    name: stocksignalpro
    runtime: python
    region: oregon
    plan: free
    buildCommand: |
      python -m ensurepip --upgrade
      python -m pip install pip==25.1 setuptools wheel
      apt-get update && apt-get install -y wkhtmltopdf
      python -m pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: "your-secure-secret-key-replace-this"  # Replace with a secure key in production
      - key: DATABASE_URL
        value: sqlite:///stock_analysis.db
      - key: PYTHON_VERSION
        value: 3.9.7
    healthCheckPath: /
    autoDeploy: true
