services:
  - type: web
    name: stocksignalpro
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      apt-get update -y
      apt-get install -y wkhtmltopdf
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:///stock_analysis.db
      - key: SECRET_KEY
        value: your-secret-key-here
    healthCheckPath: /
    autoDeploy: true
