services:
  - type: web
    name: stocksignalpro
    env: python
    region: oregon
    plan: free
    buildCommand: |
      # Install system dependencies
      apt-get update -y
      apt-get install -y wkhtmltopdf xvfb
      # Install Python dependencies
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///stock_analysis.db
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: PYTHONUNBUFFERED
        value: "true"
    healthCheckPath: /
    autoDeploy: true
