services:
  - type: web
    name: stocksignalpro
    runtime: python
    region: oregon
    plan: free
    buildCommand: |
      # Install system dependencies
      apt-get update -y
      apt-get install -y wkhtmltopdf xvfb
      # Create symlink for wkhtmltopdf
      ln -s /usr/bin/wkhtmltopdf /usr/local/bin/wkhtmltopdf
      # Install Python dependencies
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: |
      # Start Xvfb
      Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      # Set display for wkhtmltopdf
      export DISPLAY=:99
      gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///stock_analysis.db
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: PYTHONUNBUFFERED
        value: "true"
    healthCheckPath: /
    autoDeploy: true